apiVersion: devops.alauda.io/v1alpha1
kind: PipelineTaskTemplate
metadata:
  name: alauda-nodejs
  annotations:
    alauda.io/displayName.zh-CN: NodeJS构建
    alauda.io/displayName.en: NodeJS Build
    alauda.io/description.zh-CN: 构建NodeJs程序
    alauda.io/description.en: Build a NodeJs project
    alauda.io/readme.zh-CN: 构建NodeJs程序
    alauda.io/readme.en: Build a NodeJs project
    alauda.io/version: "2.1.1"
    alauda.io/style.icon: ""
  labels:
    category: Nodejs
spec:
  engine: gotpl
  body: |+
    script {
        dir(env.FOLDER) {
            container('chrome') {
                {{- if .unitTestCommand }}
                release.stageRun({
                  try {
                    sh script: """{{.unitTestCommand}}""", label: "unit tests..."
                  } finally {
                  {{- if .junitTestReport }}
                    junit allowEmptyResults: true, testResults: "{{.junitTestReport}}"
                  {{- else }}
                    echo "no test reports to capture..."
                  {{- end }}
                  }
                },[stage: "Unit test"])
                {{- end }}
                release.stageRun({
                  sh script: """{{.buildCommand}}""", label: "building..."
                }, [stage: "Build"])
            }
            
            container('tools') {
                {{- if .CodeQualityBinding}}
                env.SONAR_BINDING = "{{.CodeQualityBinding.name}}"
                deploy.scan("", "", "", ".", false, "", "", false).start()
                {{- end }}
            }
        }
    }
  arguments:
    - name: "buildCommand"
      schema:
        type: string
      display:
        type: code
        name:
          zh-CN: "构建命令"
          en: "Build Command"
        description:
          zh-CN: "自定义更详细的构建命令。默认为：go build"
          en: "build command. Defaults to: go build"
      required: false
      default: 'make build'
    - name: "unitTestCommand"
      schema:
        type: string
      display:
        type: code
        name:
          zh-CN: "单元测试命令"
          en: "UnitTest command"
        description:
          zh-CN: "单元测试命令"
          en: "UnitTest command"
      required: false
      default: ''
    - name: "junitTestReport"
      schema:
        type: string
      display:
        type: string
        name:
          zh-CN: "JUnit 单元测试报告路径"
          en: "JUnit report path"
        description:
          zh-CN: "JUnit 单元测试报告路径"
          en: "JUnit report path"
      required: false
      default: 'pkg/**/*.xml'
    - name: "CodeQualityBinding"
      schema:
        type: alauda.io/toolbinding
      display:
        type: alauda.io/toolbinding
        args:
          bindingKind: codequalitytool
          bindingToolType: Sonarqube
        name:
          zh-CN: "SonarQube 实例"
          en: "SonarQube instance"
        description:
          zh-CN: "选择要使用的 SonarQube 实例"
          en: "Select a SonarQube binding"
      required: false
