apiVersion: devops.alauda.io/v1alpha1
kind: PipelineTemplate
metadata:
  name: AllParametersTemplate
  namespace: default
  annotations:
    alauda.io/displayName.zh-CN: "All params temp 中文"
    alauda.io/displayName.en: "All params temp english"
    alauda.io/description.zh-CN: "All params temp 中文描述"
    alauda.io/description.en: "All params temp english description"
    alauda.io/version: "0.1.11"
    alauda.io/style.icon: golang,docker,sonarqube,kubernetes,python,nodejs
  labels:
    category: All
spec:
  engine: graph
  withSCM: true
  agent:
    label: base
  stages:
    - name: All
      tasks:
        - name: AllParametersTask
          kind: PipelineTaskTemplate
          type: AllParametersTask
  arguments:
    - displayName:
        zh-CN: "基本参数"
        en: "Basic paramters"
      items:
        - name: "Boolean"
          binding:
            - AllParametersTask.args.Boolean
          schema:
            type: boolean
          display:
            type: boolean
            name:
              zh-CN: "布尔"
              en: "Boolean"
            description:
              zh-CN: "布尔 描述"
              en: "boolean description"
            value: false
        - name: "StringWithDefault"
          binding:
            - AllParametersTask.args.StringWithDefault
          schema:
            type: string
          required: false
          default: "has a value"
          display:
            type: string
            name:
              zh-CN: "默认值的字符串"
              en: "String with default"
            description:
              zh-CN: "带默认值的字符串参数"
              en: "String parameter with default value"
          relation:
            - action: show
              when:
                name: Boolean
                value: true
        - name: "StringNoDefaultRequired"
          binding:
            - AllParametersTask.args.StringNoDefaultRequired
          schema:
            type: string
          required: true
          display:
            type: string
            advanced: true
            name:
              zh-CN: "必填没有默认值的字符串"
              en: "Compulsory string without default"
            description:
              zh-CN: "必填没有默认值的字符串描述"
              en: "Compulsory string without default description"
        - name: "CodeWithDefault"
          binding:
            - AllParametersTask.args.CodeWithDefault
          schema:
            type: string
          required: false
          default: "has a value"
          display:
            type: code
            name:
              zh-CN: "默认值的代码"
              en: "code with default"
            description:
              zh-CN: "带默认值的代码参数. 如果不填值这个模版会渲染失败"
              en: "Code parameter with default value"
        - name: "CodeNoDefaultRequired"
          binding:
            - AllParametersTask.args.CodeNoDefaultRequired
          schema:
            type: string
          required: true
          display:
            type: code
            advanced: true
            name:
              zh-CN: "必填没有默认值的代码"
              en: "Compulsory code without default"
            description:
              zh-CN: "必填没有默认值的代码描述"
              en: "Compulsory code without default description"
    - displayName:
        zh-CN: "代码仓库"
        en: "Code Repository"
      items:
        - name: "CodeRepoRequired"
          binding:
            - AllParametersTask.args.CodeRepoRequired
          schema:
            type: alauda.io/coderepositorymix
          required: true
          display:
            type: alauda.io/coderepositorymix
            name:
              zh-CN: "代码仓库"
              en: "Code Repository"
            description:
              zh-CN: "选择已为项目分配的代码仓库"
              en: "Select a code repository for the project."
        - name: "CodeRepoBranch"
          binding:
            - AllParametersTask.args.CodeRepoBranch
          schema:
            type: string
          required: true
          display:
            type: alauda.io/codebranch
            name:
              zh-CN: "代码仓库分支"
              en: "Code Repository branch"
            description:
              zh-CN: "选择已为项目分配的代码仓库分支"
              en: "Select a code repository branch"
            related: CodeRepoRequired
    - displayName:
        zh-CN: "镜像仓库"
        en: "Image Repository"
      items:
        - name: "ImageRepositoryRequired"
          binding:
            - AllParametersTask.args.ImageRepositoryRequired
          schema:
            type: alauda.io/dockerimagerepositorymix
          required: true
          display:
            type: alauda.io/dockerimagerepositorymix
            name:
              zh-CN: "镜像仓库"
              en: Repository
            description:
              zh-CN: "选择或者输入镜像仓库"
              en: "Image repo description"
        - name: "ImageRepositoryPull"
          binding:
            - AllParametersTask.args.ImageRepositoryPull
          schema:
            type: alauda.io/dockerimagerepositorypullmix
          required: false
          display:
            type: alauda.io/dockerimagerepositorypullmix
            name:
              zh-CN: "pull镜像仓库"
              en: Repository pull
            description:
              zh-CN: "pull 选择或者输入镜像仓库"
              en: "pull Image repo description"
    - displayName:
        zh-CN: "绑定"
        en: "Binding"
      items:
        - name: "CodeQualityBinding"
          binding:
            - AllParametersTask.args.CodeQualityBinding
          schema:
            type: alauda.io/toolbinding
          display:
            type: alauda.io/toolbinding
            args:
              bindingKind: codequalitytool
              bindingToolType: Sonarqube
            name:
              zh-CN: "SonarQube 实例"
              en: "SonarQube instance"
            description:
              zh-CN: "选择要使用的 SonarQube 实例"
              en: "Select a SonarQube binding"
          required: true
    - displayName:
        zh-CN: "集群与应用"
        en: "Cluster App"
      items:
        - name: clusterName
          schema:
            type: string
          binding:
          - AllParametersTask.args.clusterName
          display:
            type: alauda.io/clustername
            name:
              zh-CN: "集群"
              en: "cluster"
            description:
              zh-CN: "需要更新的应用所在的集群"
              en: "cluster"
          required: true
          value: ""
        - name: namespace
          schema:
            type: string
          binding:
          - AllParametersTask.args.namespace
          display:
            type: alauda.io/namespace
            name:
              zh-CN: "命名空间"
              en: "namespace"
            description:
              zh-CN: "需要更新的应用所在的命名空间"
              en: "namespace"
            related: clusterName
          required: true
          value: ""
        - name: serviceName
          schema:
            type: string
          binding:
            - AllParametersTask.args.serviceName
          display:
            type: alauda.io/servicenamemix
            name:
              zh-CN: "应用"
              en: "application"
            description:
              zh-CN: "需要更新的应用名称、组件类型、组件名称"
              en: "application"
            related: namespace
          required: true
          value: ""
        - name: containerName
          schema:
            type: string
          binding:
            - AllParametersTask.args.containerName
          display:
            type: alauda.io/containername
            name:
              zh-CN: "容器"
              en: "container"
            description:
              zh-CN: "需要更新的容器实例名称"
              en: "container"
            related: serviceName
          required: true
          value: ""
        - name: "command"
          schema:
            type: string
          required: false
          binding:
          - AllParametersTask.args.command
          value: ""
          display:
            type: string
            advanced: true
            name:
              zh-CN: "启动命令"
              en: "command"
            description:
              zh-CN: "即 command，相当于 Dockerfile 中的 ENTRYPOINT 命令。如果没有指定启动命令，将使用容器镜像中的 ENTRYPOINT"
              en: "command"
        - name: "args"
          schema:
            type: string
          required: false
          binding:
          - AllParametersTask.args.args
          display:
            type: string
            advanced: true
            name:
              zh-CN: "参数"
              en: "args"
            description:
              zh-CN: "即 args，相当于 Dockerfile 中的 CMD，负责提供启动命令的命令参数。如果没有指定参数，将使用容器镜像中的 CMD"
              en: "args"
        - name: timeout
          schema:
            type: string
          binding:
            - AllParametersTask.args.timeout
          display:
            type: string
            advanced: true
            name:
              zh-CN: "超时时间（秒）"
              en: "Timeout (s)"
            description:
              zh-CN: "当前任务的执行时间若超过超时时间，则会中止任务，流水线变为失败状态"
              en: ""
          required: true
          default: '300'
          value: ""
